### ISSUE TITLE
Flashing black box in corner of output

### ISSUE THREAD

**Issue by hellocatfood** [chidea/FBpyGIF#24]
I've used FBpyGIF with a gif and the color test mode and on each occasion there is a blinking black box in the bottom-left of the screen. This appears to be the terminal input cursor. Here's a video I recorded with my phone:

![new](https://user-images.githubusercontent.com/151947/62659525-85d8f580-b963-11e9-83ec-cbcdf4aed00c.gif)

Tested on a Raspberry Pi 2 B+ and Raspberry pi 3

**Comment by chidea** [comment]
It's because your console has a blinking cursor.

`echo -e "\e[?1c"` if you're on it's physical terminal
`sudo bash -c 'echo -e "\e[?1c" > /dev/tty0'` if you're on ssh
will fix it. Putting the first one in `.bashrc` will make it persistent.

The full information behind is in page below.
https://linuxgazette.net/137/anonymous.html

On Raspberry Pi, it can instead be fixed by adding below line to the file `/boot/cmdline.txt`
```vt.global_cursor_default=0```

Only one line of `print` function in this program would have fixed this issue but I'm not touching this library right now.
There is a much fast and efficient rust version of this program planned to be written soon and this issue is going to be fixed there.

**Comment by hellocatfood** [comment]
Thanks, that fixed it! Looking forward to the new version
